apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: openshift-gitops
spec:
  project: default
  source:
    chart: backstage
    repoURL: https://backstage.github.io/charts
    targetRevision: 0.17.0
    helm:
      valueFiles:
      - backstage-values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: backstage