apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/ansonmez/demo-gitops
    targetRevision: master
    path: apps/backstage
  destination:
    server: "https://kubernetes.default.svc"
    namespace: backstage
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
