kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: skupper-proj2
spec:
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backstage-pipeline-proj2-admin
  namespace: skupper-proj2
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: backstage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
